version: "3.9"

services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    ports:
      - "5000:5000"
    environment:
      - LT_CORS_ALLOWED_ORIGINS=*
      - LT_HOST=0.0.0.0
      - LT_PORT=5000
    restart: always
